title: 식탁보 프로젝트
description: >- # this means to ignore newlines until "baseurl:"
  윈도우 10 버전 1909부터 추가된 윈도우 샌드박스를 활용하여, 컴퓨터에서 인터넷 뱅킹을 사용하거나, 전자정부 인터넷 서비스를 사용할 때 설치되는 여러가지 클라이언트 보안 프로그램을 실제 컴퓨터 환경에 영향을 주지 않고 사용할 수 있도록 도와주는 프로그램입니다.
url: "https://yourtablecloth.app" # the base hostname & protocol for your site, e.g. http://example.com
include:
  - .well-known
